### ISSUE TITLE
Empty popup with file comments

### ISSUE THREAD

**Issue by Kcko** [garetht/sublime-scss-expander#2]
When i start scss file with my own comment i get empty popup.
/**
- Copyright (C) 2014 User
- @file _navigation.scss
  *
- changelog
- 2014-09-12[14:40:07]
  *
- @author user
- @version 1.0-rc
- @link http://semver.org/
  */

When i remove, plugin works. Could u fix please?

**Comment by garetht** [comment]
Should be fixed in release 0.3.2
